import {
  Profile,
  EventTheme,
  MenuCategory,
  MenuItem,
  Package,
  RentalItem,
  Reservation,
  Payment,
  Notification,
} from '@/types/database';

export const INITIAL_PROFILES: Profile[] = [
  {
    id: '00000000-0000-0000-0000-000000000001',
    name: 'Admin User',
    phone: '0917-888-0001',
    role: 'admin',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '00000000-0000-0000-0000-000000000002',
    name: 'Maria Santos',
    phone: '0918-123-4567',
    role: 'customer',
    created_at: '2026-02-15T00:00:00Z',
  },
  {
    id: '00000000-0000-0000-0000-000000000003',
    name: 'Juan Dela Cruz',
    phone: '0922-987-6543',
    role: 'customer',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: '00000000-0000-0000-0000-000000000004',
    name: 'Beatrice Lim',
    phone: '0917-555-1212',
    role: 'customer',
    created_at: '2026-03-20T00:00:00Z',
  },
];

export const INITIAL_THEMES: EventTheme[] = [
  {
    id: 1,
    name: 'Wedding',
    tagline: 'Your perfect day, exquisitely served',
    description:
      'Timeless romantic banquet styling with delicate table runners, elegant floral backdrops, warm fairy lights, and VIP couple dining arrangements.',
    image_url: '/images/2 PIC.jpg',
    is_active: true,
  },
  {
    id: 2,
    name: 'Birthday Celebration',
    tagline: 'Celebrate every milestone in grand style',
    description:
      'Vibrant festive balloons, dynamic balloon arches, customized stage backdrop, themed dessert table, and party favors setup.',
    image_url: '/images/5.jpg',
    is_active: true,
  },
  {
    id: 3,
    name: 'Debut Elegance',
    tagline: 'A modern fairytale debutante celebration',
    description:
      'Glamorous 18-roses and 18-candles grand reception, illuminated floral centerpieces, chandelier accents, and plush debutante throne.',
    image_url: '/images/1 PIC.jpg',
    is_active: true,
  },
  {
    id: 4,
    name: 'Corporate Gala',
    tagline: 'Professional hospitality for distinguished corporate events',
    description:
      'Sleek executive banquet setup, podium styling, neat linen presentation, and polished buffet service for conferences and annual galas.',
    image_url: '/images/4 PIC.jpg',
    is_active: true,
  },
  {
    id: 5,
    name: 'Filipino Fiesta',
    tagline: 'Authentic traditional Pinoy feast for festive gatherings',
    description:
      'Warm native bamboo accents, vibrant banner streamers, traditional banana leaf accents, and hearty heirloom banquet service.',
    image_url: '/images/3 PIC.jpg',
    is_active: true,
  },
  {
    id: 6,
    name: 'Christening & Dedication',
    tagline: 'Blessings and joyful memories for the little one',
    description:
      'Soft pastel palettes, delicate cloud balloons, angel wings or carousel backdrop styling, and family-friendly buffet arrangements.',
    image_url: '/images/6.jpg',
    is_active: true,
  },
];

export const INITIAL_CATEGORIES: MenuCategory[] = [
  { id: 1, name: 'Appetizers', display_order: 1 },
  { id: 2, name: 'Soup & Salad', display_order: 2 },
  { id: 3, name: 'Main Course', display_order: 3 },
  { id: 4, name: 'Seafood Special', display_order: 4 },
  { id: 5, name: 'Rice & Noodles', display_order: 5 },
  { id: 6, name: 'Desserts & Drinks', display_order: 6 },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: 1,
    category_id: 1,
    name: 'Lumpiang Shanghai',
    description: 'Crispy golden fried pork and vegetable spring rolls with sweet & sour dip',
    price_per_head: 120,
    is_available: true,
  },
  {
    id: 2,
    category_id: 1,
    name: 'Dynamite Cheese Sticks',
    description: 'Green finger chili stuffed with mild cheddar and cream cheese, fried golden',
    price_per_head: 135,
    is_available: true,
  },
  {
    id: 3,
    category_id: 1,
    name: 'Savory Beef Canapés',
    description: 'Herb toasted crostini topped with tender roast beef slivers and caramelized onion',
    price_per_head: 150,
    is_available: true,
  },
  {
    id: 4,
    category_id: 1,
    name: 'Pork Siomai Dimsum',
    description: 'Steamed homemade pork and shrimp dumplings with calamansi chili garlic soy',
    price_per_head: 110,
    is_available: true,
  },
  {
    id: 5,
    category_id: 2,
    name: 'Cream of Wild Mushroom',
    description: 'Velvety slow-simmered forest mushrooms with fresh cream and butter croutons',
    price_per_head: 110,
    is_available: true,
  },
  {
    id: 6,
    category_id: 2,
    name: 'Sinigang na Hipon Broth',
    description: 'Tamarind sour soup with fresh river prawns and native garden vegetables',
    price_per_head: 160,
    is_available: true,
  },
  {
    id: 7,
    category_id: 2,
    name: 'Kani & Mango Garden Salad',
    description: 'Crisp romaine, sweet ripe mango cubes, Japanese crab stick, and sesame vinaigrette',
    price_per_head: 140,
    is_available: true,
  },
  {
    id: 8,
    category_id: 3,
    name: 'Slow-Roasted Beef Caldereta',
    description: 'Fork-tender beef brisket slow-cooked in rich tomato liver sauce with bell peppers and cheese',
    price_per_head: 295,
    is_available: true,
  },
  {
    id: 9,
    category_id: 3,
    name: 'Crispy Lechon Kawali',
    description: 'Crispy pork belly with crackling golden skin served with spiced liver sauce',
    price_per_head: 280,
    is_available: true,
  },
  {
    id: 10,
    category_id: 3,
    name: 'Chicken Inasal Bacolod Style',
    description: 'Grilled lemongrass and annatto-marinated chicken cuts with chicken oil garlic rice dip',
    price_per_head: 220,
    is_available: true,
  },
  {
    id: 11,
    category_id: 3,
    name: 'Classic Kare-Kareng Baka',
    description: 'Slow-cooked beef shanks and tripe in rich savory peanut sauce with sautéed bagoong alamang',
    price_per_head: 310,
    is_available: true,
  },
  {
    id: 12,
    category_id: 3,
    name: 'Crispy Pata Premiere',
    description: 'Deep-fried pork knuckle with crispy blistered skin and spicy vinegar soy dip',
    price_per_head: 350,
    is_available: true,
  },
  {
    id: 13,
    category_id: 3,
    name: 'Pork Ribs Barbecue',
    description: 'Tender grilled pork loin ribs glazed in smoky sweet honey barbecue marinade',
    price_per_head: 260,
    is_available: true,
  },
  {
    id: 14,
    category_id: 4,
    name: 'Garlic Butter Tiger Prawns',
    description: 'Sautéed succulent prawns tossed in golden garlic butter and parsley',
    price_per_head: 340,
    is_available: true,
  },
  {
    id: 15,
    category_id: 4,
    name: 'Sweet & Sour Lapu-Lapu',
    description: 'Crispy fried local grouper topped with sweet and tangy bell pepper ginger glaze',
    price_per_head: 320,
    is_available: true,
  },
  {
    id: 16,
    category_id: 5,
    name: 'Special Pancit Canton Guisado',
    description: 'Egg noodles stir-fried with chicken strips, shrimp, pork meatballs, and crisp vegetables',
    price_per_head: 130,
    is_available: true,
  },
  {
    id: 17,
    category_id: 5,
    name: 'Pancit Sotanghon Guisado',
    description: 'Silky glass vermicelli noodles with shredded chicken, wood-ear mushrooms, and toasted garlic',
    price_per_head: 135,
    is_available: true,
  },
  {
    id: 18,
    category_id: 5,
    name: 'Fragrant Pandan Steamed Rice',
    description: 'Fluffy jasmine rice cooked with fresh pandan leaves',
    price_per_head: 35,
    is_available: true,
  },
  {
    id: 19,
    category_id: 5,
    name: 'Toasted Garlic Golden Rice',
    description: 'Jasmine rice fried with fragrant roasted minced garlic and spring onion',
    price_per_head: 45,
    is_available: true,
  },
  {
    id: 20,
    category_id: 5,
    name: 'Savory Java Rice',
    description: 'Annatto-infused rice with subtle herbs and sweet corn kernels',
    price_per_head: 50,
    is_available: true,
  },
  {
    id: 21,
    category_id: 6,
    name: 'Royal Leche Flan',
    description: 'Velvety smooth caramel custard made with rich egg yolks and condensed milk',
    price_per_head: 95,
    is_available: true,
  },
  {
    id: 22,
    category_id: 6,
    name: 'Buko Pandan Supreme',
    description: 'Young coconut strips and fragrant pandan jelly in sweetened rich cream',
    price_per_head: 90,
    is_available: true,
  },
  {
    id: 23,
    category_id: 6,
    name: 'Classic Ube Halaya',
    description: 'Slow-stirred purple yam jam with toasted coconut latik topping',
    price_per_head: 105,
    is_available: true,
  },
  {
    id: 24,
    category_id: 6,
    name: 'Chilled Mango Float Cups',
    description: 'Graham cracker crust layered with fresh sweet Manila mango and whipped cream',
    price_per_head: 95,
    is_available: true,
  },
  {
    id: 25,
    category_id: 6,
    name: 'Traditional Sago\'t Gulaman',
    description: 'Chilled brown sugar and pandan syrup with chewy tapioca pearls and grass jelly',
    price_per_head: 60,
    is_available: true,
  },
  {
    id: 26,
    category_id: 6,
    name: 'Fresh Calamansi Honey Cooler',
    description: 'Zesty freshly-squeezed native calamansi juice with wild forest honey',
    price_per_head: 65,
    is_available: true,
  },
];

export const INITIAL_PACKAGES: Package[] = [
  {
    id: 1,
    name: 'Silver Buffet',
    description:
      '1 Soup, 1 Appetizer, 3 Main Courses (Pork, Chicken, Fish), 1 Noodle, 1 Rice, 1 Dessert, Bottomless Iced Tea. Complete buffet setup with floral arrangement and trained waiters.',
    price_per_pax: 450,
    min_pax: 50,
    theme_id: null,
  },
  {
    id: 2,
    name: 'Gold Feast',
    description:
      '1 Soup, 2 Appetizers, 4 Main Courses (Beef, Pork, Chicken, Seafood), 1 Noodle, 2 Rice varieties, 2 Desserts, Bottomless Specialty Cooler. Complete themed setup with centerpiece on all guest tables.',
    price_per_pax: 650,
    min_pax: 50,
    theme_id: null,
  },
  {
    id: 3,
    name: 'Platinum Royal Banquet',
    description:
      'Full wedding grand reception: 2 Soups, 3 Appetizers, 5 Premium Mains including Roasted Beef Caldereta & Tiger Prawns, 2 Noodles, 3 Gourmet Desserts, Champagne toast, VIP Table service & centerpiece.',
    price_per_pax: 950,
    min_pax: 80,
    theme_id: 1,
  },
  {
    id: 4,
    name: 'Debutante Special Feast',
    description:
      'Curated for 18th Birthdays: 2 Appetizers, 4 Main Courses, 1 Pasta/Noodle, Steamed Rice, 2 Desserts, Mocktail fountain, Debutante stage decor and 18-roses arrangement coordination.',
    price_per_pax: 550,
    min_pax: 60,
    theme_id: 3,
  },
  {
    id: 5,
    name: 'Corporate Lite Executive',
    description:
      'Tailored for conferences, seminars, and corporate meetings: Quick-serve hot buffet with 3 Mains, 1 Vegetable/Salad, Rice, Dessert, and Fresh Brewed Coffee / Iced Tea station.',
    price_per_pax: 400,
    min_pax: 30,
    theme_id: 4,
  },
];

export const INITIAL_RENTAL_ITEMS: RentalItem[] = [
  {
    id: 1,
    name: 'Tiffany Gold Chairs',
    category: 'Seating',
    rate_per_unit: 85,
    stock_quantity: 350,
    is_available: true,
  },
  {
    id: 2,
    name: 'Round Banquet Tables (10-Seater)',
    category: 'Tables',
    rate_per_unit: 350,
    stock_quantity: 45,
    is_available: true,
  },
  {
    id: 3,
    name: 'Stainless Roll-Top Chafing Dish',
    category: 'Food Service',
    rate_per_unit: 250,
    stock_quantity: 40,
    is_available: true,
  },
  {
    id: 4,
    name: 'Full Drop Embroidered Table Linen',
    category: 'Linens',
    rate_per_unit: 120,
    stock_quantity: 60,
    is_available: true,
  },
  {
    id: 5,
    name: 'Spandex Chair Covers with Gold Satin Bow',
    category: 'Linens',
    rate_per_unit: 45,
    stock_quantity: 400,
    is_available: true,
  },
  {
    id: 6,
    name: 'Cocktail Highboy Tables with Spandex Cover',
    category: 'Tables',
    rate_per_unit: 200,
    stock_quantity: 25,
    is_available: true,
  },
  {
    id: 7,
    name: 'Mobile Sound System with 2 Cordless Mics',
    category: 'Audio & Lights',
    rate_per_unit: 2500,
    stock_quantity: 5,
    is_available: true,
  },
  {
    id: 8,
    name: 'LED Uplighting Set (8 Warm Amber Pars)',
    category: 'Audio & Lights',
    rate_per_unit: 1800,
    stock_quantity: 6,
    is_available: true,
  },
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 1,
    booking_code: 'RES-2026-0001',
    customer_id: '00000000-0000-0000-0000-000000000002',
    theme_id: 1,
    package_id: 3,
    event_date: '2026-10-24',
    event_time: '17:00',
    venue_address: 'Fernwood Gardens, Quezon City',
    guest_count: 150,
    special_requests: 'Allergies: No peanuts for 2 VIP guests. Warm amber uplighting preferred.',
    total_amount: 142500,
    status: 'confirmed',
    created_at: '2026-09-02T10:00:00Z',
    rentals: [
      { id: 1, reservation_id: 1, rental_item_id: 1, quantity: 150, subtotal: 12750, rental_item: INITIAL_RENTAL_ITEMS[0] },
      { id: 2, reservation_id: 1, rental_item_id: 2, quantity: 15, subtotal: 5250, rental_item: INITIAL_RENTAL_ITEMS[1] },
      { id: 3, reservation_id: 1, rental_item_id: 8, quantity: 2, subtotal: 3600, rental_item: INITIAL_RENTAL_ITEMS[7] },
    ],
  },
  {
    id: 2,
    booking_code: 'RES-2026-0002',
    customer_id: '00000000-0000-0000-0000-000000000003',
    theme_id: 2,
    package_id: 2,
    event_date: '2026-10-28',
    event_time: '11:30',
    venue_address: 'San Antonio Clubhouse, Makati City',
    guest_count: 80,
    special_requests: 'Lightning McQueen backdrop setup for child 7th birthday.',
    total_amount: 52000,
    status: 'confirmed',
    created_at: '2026-09-06T14:30:00Z',
    rentals: [
      { id: 4, reservation_id: 2, rental_item_id: 6, quantity: 4, subtotal: 800, rental_item: INITIAL_RENTAL_ITEMS[5] },
    ],
  },
  {
    id: 3,
    booking_code: 'RES-2026-0003',
    customer_id: '00000000-0000-0000-0000-000000000004',
    theme_id: 3,
    package_id: 4,
    event_date: '2026-11-05',
    event_time: '18:00',
    venue_address: 'The Blue Leaf Pavilion, Taguig',
    guest_count: 120,
    special_requests: '18 roses coordinator table, Cinderella theme palette.',
    total_amount: 66000,
    status: 'in_progress',
    created_at: '2026-09-08T09:15:00Z',
    rentals: [
      { id: 5, reservation_id: 3, rental_item_id: 1, quantity: 120, subtotal: 10200, rental_item: INITIAL_RENTAL_ITEMS[0] },
      { id: 6, reservation_id: 3, rental_item_id: 7, quantity: 1, subtotal: 2500, rental_item: INITIAL_RENTAL_ITEMS[6] },
    ],
  },
  {
    id: 4,
    booking_code: 'RES-2026-0004',
    customer_id: '00000000-0000-0000-0000-000000000002',
    theme_id: 4,
    package_id: 5,
    event_date: '2026-11-12',
    event_time: '09:00',
    venue_address: 'BGC Tower Function Hall 4B, Taguig',
    guest_count: 60,
    special_requests: 'Coffee station setup 30 minutes prior to keynote.',
    total_amount: 24000,
    status: 'pending',
    created_at: '2026-09-13T11:00:00Z',
  },
  {
    id: 5,
    booking_code: 'RES-2026-0005',
    customer_id: '00000000-0000-0000-0000-000000000003',
    theme_id: 5,
    package_id: 1,
    event_date: '2026-11-20',
    event_time: '12:00',
    venue_address: 'Barangay San Isidro Community Hall, Pasig',
    guest_count: 100,
    special_requests: 'Additional rice warmer requested.',
    total_amount: 45000,
    status: 'pending',
    created_at: '2026-09-14T15:20:00Z',
  },
  {
    id: 6,
    booking_code: 'RES-2026-0006',
    customer_id: '00000000-0000-0000-0000-000000000004',
    theme_id: 6,
    package_id: 2,
    event_date: '2026-11-25',
    event_time: '10:30',
    venue_address: 'Holy Trinity Hall, San Juan',
    guest_count: 75,
    special_requests: 'Pastel blue theme with angel wings photo booth.',
    total_amount: 48750,
    status: 'pending',
    created_at: '2026-09-15T08:45:00Z',
  },
  {
    id: 7,
    booking_code: 'RES-2026-0007',
    customer_id: '00000000-0000-0000-0000-000000000002',
    theme_id: 1,
    package_id: 3,
    event_date: '2026-08-15',
    event_time: '16:00',
    venue_address: 'Villa Milagros Events Place, Rodriguez Rizal',
    guest_count: 180,
    special_requests: 'Completed wedding banquet. Exceptional compliments on Kare-Kare.',
    total_amount: 171000,
    status: 'completed',
    created_at: '2026-08-01T12:00:00Z',
    rentals: [
      { id: 7, reservation_id: 7, rental_item_id: 1, quantity: 180, subtotal: 15300, rental_item: INITIAL_RENTAL_ITEMS[0] },
    ],
  },
  {
    id: 8,
    booking_code: 'RES-2026-0008',
    customer_id: '00000000-0000-0000-0000-000000000003',
    theme_id: 4,
    package_id: 5,
    event_date: '2026-08-22',
    event_time: '08:30',
    venue_address: 'Ortigas Center Boardroom, Pasig',
    guest_count: 40,
    special_requests: 'Quarterly shareholder lunch.',
    total_amount: 16000,
    status: 'completed',
    created_at: '2026-08-10T16:00:00Z',
  },
  {
    id: 9,
    booking_code: 'RES-2026-0009',
    customer_id: '00000000-0000-0000-0000-000000000004',
    theme_id: 2,
    package_id: 1,
    event_date: '2026-09-01',
    event_time: '14:00',
    venue_address: 'Valle Verde 2 Clubhouse, Pasig',
    guest_count: 90,
    special_requests: '50th Golden Jubilee Birthday.',
    total_amount: 40500,
    status: 'completed',
    created_at: '2026-08-25T11:20:00Z',
  },
  {
    id: 10,
    booking_code: 'RES-2026-0010',
    customer_id: '00000000-0000-0000-0000-000000000002',
    theme_id: 5,
    package_id: 2,
    event_date: '2026-09-10',
    event_time: '18:00',
    venue_address: 'Marikina River Park Pavilion',
    guest_count: 110,
    special_requests: 'Alumni Reunion Feast.',
    total_amount: 71500,
    status: 'completed',
    created_at: '2026-09-01T13:40:00Z',
  },
  {
    id: 11,
    booking_code: 'RES-2026-0011',
    customer_id: '00000000-0000-0000-0000-000000000003',
    theme_id: 1,
    package_id: 2,
    event_date: '2026-10-05',
    event_time: '15:00',
    venue_address: 'Taal Vista Hotel Viewdeck, Tagaytay',
    guest_count: 70,
    special_requests: 'Client rescheduled to next year due to overseas travel.',
    total_amount: 45500,
    status: 'cancelled',
    created_at: '2026-09-01T09:00:00Z',
  },
  {
    id: 12,
    booking_code: 'RES-2026-0012',
    customer_id: '00000000-0000-0000-0000-000000000004',
    theme_id: 3,
    package_id: 4,
    event_date: '2026-09-18',
    event_time: '17:00',
    venue_address: 'Oasis Manila, New Manila, QC',
    guest_count: 100,
    special_requests: 'Cancelled by client request.',
    total_amount: 55000,
    status: 'cancelled',
    created_at: '2026-09-10T14:15:00Z',
  },
  {
    id: 13,
    booking_code: 'RES-2026-0013',
    customer_id: '00000000-0000-0000-0000-000000000002',
    theme_id: 1,
    package_id: 3,
    event_date: '2026-12-10',
    event_time: '17:30',
    venue_address: 'Glass Garden Events Venue, Pasig',
    guest_count: 200,
    special_requests: 'Winter wonderland floral motif.',
    total_amount: 190000,
    status: 'confirmed',
    created_at: '2026-09-10T15:00:00Z',
    rentals: [
      { id: 8, reservation_id: 13, rental_item_id: 1, quantity: 200, subtotal: 17000, rental_item: INITIAL_RENTAL_ITEMS[0] },
    ],
  },
  {
    id: 14,
    booking_code: 'RES-2026-0014',
    customer_id: '00000000-0000-0000-0000-000000000003',
    theme_id: 2,
    package_id: 2,
    event_date: '2026-12-18',
    event_time: '12:00',
    venue_address: 'Acropolis Clubhouse, Quezon City',
    guest_count: 85,
    special_requests: 'Family reunion and Christmas birthday.',
    total_amount: 55250,
    status: 'confirmed',
    created_at: '2026-09-12T10:30:00Z',
  },
  {
    id: 15,
    booking_code: 'RES-2026-0015',
    customer_id: '00000000-0000-0000-0000-000000000004',
    theme_id: 4,
    package_id: 5,
    event_date: '2026-12-22',
    event_time: '18:00',
    venue_address: 'Grand Hyatt Ballroom, Taguig',
    guest_count: 150,
    special_requests: 'Annual Company Year-End Thanksgiving Banquet.',
    total_amount: 60000,
    status: 'confirmed',
    created_at: '2026-09-14T09:00:00Z',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 1,
    reservation_id: 1,
    amount: 71250,
    payment_type: 'downpayment',
    payment_method: 'gcash',
    reference_number: 'GCASH-20260902-984210',
    proof_image_url: '/images/receipt_sample.svg',
    status: 'verified',
    paid_at: '2026-09-03T10:15:00Z',
    verified_at: '2026-09-04T09:30:00Z',
  },
  {
    id: 2,
    reservation_id: 2,
    amount: 26000,
    payment_type: 'downpayment',
    payment_method: 'bank_transfer',
    reference_number: 'BDO-REF-492019482',
    proof_image_url: '/images/receipt_sample.svg',
    status: 'verified',
    paid_at: '2026-09-07T11:00:00Z',
    verified_at: '2026-09-08T14:20:00Z',
  },
  {
    id: 3,
    reservation_id: 3,
    amount: 33000,
    payment_type: 'downpayment',
    payment_method: 'gcash',
    reference_number: 'GCASH-20260908-112394',
    proof_image_url: '/images/receipt_sample.svg',
    status: 'verified',
    paid_at: '2026-09-09T16:00:00Z',
    verified_at: '2026-09-10T10:00:00Z',
  },
  {
    id: 4,
    reservation_id: 7,
    amount: 85500,
    payment_type: 'downpayment',
    payment_method: 'bank_transfer',
    reference_number: 'BPI-TRF-883920114',
    proof_image_url: '/images/receipt_sample.svg',
    status: 'verified',
    paid_at: '2026-08-05T09:00:00Z',
    verified_at: '2026-08-06T11:00:00Z',
  },
  {
    id: 5,
    reservation_id: 7,
    amount: 85500,
    payment_type: 'final_balance',
    payment_method: 'credit_card',
    reference_number: 'CC-AUTH-77392104',
    proof_image_url: '/images/receipt_sample.svg',
    status: 'verified',
    paid_at: '2026-08-14T17:00:00Z',
    verified_at: '2026-08-14T17:30:00Z',
  },
  {
    id: 6,
    reservation_id: 8,
    amount: 16000,
    payment_type: 'full_payment',
    payment_method: 'bank_transfer',
    reference_number: 'BDO-CORP-9921004',
    proof_image_url: '/images/receipt_sample.svg',
    status: 'verified',
    paid_at: '2026-08-15T13:00:00Z',
    verified_at: '2026-08-16T09:00:00Z',
  },
  {
    id: 7,
    reservation_id: 9,
    amount: 40500,
    payment_type: 'full_payment',
    payment_method: 'gcash',
    reference_number: 'GCASH-20260830-449102',
    proof_image_url: '/images/receipt_sample.svg',
    status: 'verified',
    paid_at: '2026-08-28T14:00:00Z',
    verified_at: '2026-08-29T10:00:00Z',
  },
  {
    id: 8,
    reservation_id: 10,
    amount: 71500,
    payment_type: 'full_payment',
    payment_method: 'cash',
    reference_number: 'RECEIPT-OR-09482',
    proof_image_url: '/images/receipt_sample.svg',
    status: 'verified',
    paid_at: '2026-09-05T15:00:00Z',
    verified_at: '2026-09-06T11:00:00Z',
  },
  {
    id: 9,
    reservation_id: 4,
    amount: 12000,
    payment_type: 'downpayment',
    payment_method: 'gcash',
    reference_number: 'GCASH-20260914-774910',
    proof_image_url: '/images/receipt_sample.svg',
    status: 'pending_verification',
    paid_at: '2026-09-14T12:00:00Z',
    verified_at: null,
  },
  {
    id: 10,
    reservation_id: 13,
    amount: 95000,
    payment_type: 'downpayment',
    payment_method: 'bank_transfer',
    reference_number: 'METRO-TRF-66392011',
    proof_image_url: '/images/receipt_sample.svg',
    status: 'pending_verification',
    paid_at: '2026-09-15T16:20:00Z',
    verified_at: null,
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 1,
    user_id: '00000000-0000-0000-0000-000000000001',
    title: 'New Reservation Received',
    message: 'Booking RES-2026-0004 for Corporate Gala (60 pax) requires review.',
    is_read: false,
    created_at: '2026-09-13T11:05:00Z',
  },
  {
    id: 2,
    user_id: '00000000-0000-0000-0000-000000000001',
    title: 'Payment Submitted for Verification',
    message: 'Customer Maria Santos submitted ₱12,000 via GCash for RES-2026-0004.',
    is_read: false,
    created_at: '2026-09-14T12:05:00Z',
  },
  {
    id: 3,
    user_id: '00000000-0000-0000-0000-000000000001',
    title: 'High-Value Payment Alert',
    message: 'Reservation RES-2026-0013 submitted ₱95,000 downpayment via Bank Transfer.',
    is_read: false,
    created_at: '2026-09-15T16:25:00Z',
  },
  {
    id: 4,
    user_id: '00000000-0000-0000-0000-000000000002',
    title: 'Reservation Confirmed',
    message: 'Your Wedding booking RES-2026-0001 has been confirmed by management.',
    is_read: true,
    created_at: '2026-09-04T09:35:00Z',
  },
  {
    id: 5,
    user_id: '00000000-0000-0000-0000-000000000002',
    title: 'Downpayment Received',
    message: 'Thank you! Downpayment of ₱71,250.00 for RES-2026-0001 is verified.',
    is_read: true,
    created_at: '2026-09-04T09:40:00Z',
  },
  {
    id: 6,
    user_id: '00000000-0000-0000-0000-000000000003',
    title: 'Birthday Booking Confirmed',
    message: 'Your booking RES-2026-0002 for 80 pax at San Antonio Clubhouse is confirmed.',
    is_read: true,
    created_at: '2026-09-08T14:25:00Z',
  },
];

export interface DemoAccount {
  email: string;
  password: string;
  profileId: string;
}

export const INITIAL_ACCOUNTS: DemoAccount[] = [
  {
    email: 'admin@caterpro.ph',
    password: 'admin123',
    profileId: '00000000-0000-0000-0000-000000000001',
  },
  {
    email: 'customer@test.ph',
    password: 'pass123',
    profileId: '00000000-0000-0000-0000-000000000002',
  },
  {
    email: 'juan@caterpro.ph',
    password: 'pass123',
    profileId: '00000000-0000-0000-0000-000000000003',
  },
  {
    email: 'beatrice@caterpro.ph',
    password: 'pass123',
    profileId: '00000000-0000-0000-0000-000000000004',
  },
];

// Helper to get / set from localStorage with fallback to initial seed
function getStorage<T>(key: string, initial: T): T {
  try {
    const item = localStorage.getItem(`caterpro_${key}`);
    return item ? JSON.parse(item) : initial;
  } catch {
    return initial;
  }
}

function setStorage<T>(key: string, value: T): void {
  try {
    localStorage.setItem(`caterpro_${key}`, JSON.stringify(value));
  } catch (err) {
    console.error('Storage error:', err);
  }
}

export const mockStore = {
  getProfiles: () => getStorage('profiles', INITIAL_PROFILES),
  getThemes: () => getStorage('themes', INITIAL_THEMES),
  getCategories: () => getStorage('categories', INITIAL_CATEGORIES),
  getMenuItems: () => getStorage('menu_items', INITIAL_MENU_ITEMS),
  getPackages: () => getStorage('packages', INITIAL_PACKAGES),
  getRentals: () => getStorage('rentals', INITIAL_RENTAL_ITEMS),
  getReservations: () => getStorage('reservations', INITIAL_RESERVATIONS),
  getPayments: () => getStorage('payments', INITIAL_PAYMENTS),
  getNotifications: () => getStorage('notifications', INITIAL_NOTIFICATIONS),
  getAccounts: () => getStorage('accounts', INITIAL_ACCOUNTS),

  saveReservations: (items: Reservation[]) => setStorage('reservations', items),
  savePayments: (items: Payment[]) => setStorage('payments', items),
  saveMenuItems: (items: MenuItem[]) => setStorage('menu_items', items),
  savePackages: (items: Package[]) => setStorage('packages', items),
  saveThemes: (items: EventTheme[]) => setStorage('themes', items),
  saveRentals: (items: RentalItem[]) => setStorage('rentals', items),
  saveNotifications: (items: Notification[]) => setStorage('notifications', items),
  saveProfiles: (items: Profile[]) => setStorage('profiles', items),
  saveAccounts: (items: DemoAccount[]) => setStorage('accounts', items),
};
